## Prometheus server ConfigMap entries
##
serverFiles:

  ## Alerts configuration
  ## Ref: https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
  alerting_rules.yml: 
    groups:
     - name: k8s #Monitor the metrics nodes in K8S
       rules: 
        - alert: ContadorNodes
          expr: count(kube_node_created) > 3
          for: 1m
          labels:
            team: k8s #DevOps
          annotations: 
            summary: Quantidade de nodes alta
            description: "Valor: {{ $value }}"

     - name: Web #Monitor the metrics of the application
       rules: 
        - alert: WebQuantidadeAcessos
          expr: sum(rate(http_requests_total[30s])) by (app,path)) > 0.40
          for: 1m
          labels:
            team: web #DevOps
          annotations: 
            summary: Quantidade de chamadas alta
            description: "Path {{$labels.path}} Valor: {{$value}}"

  alertmanagerFiles:
    alertmanager.yml:
      global:
      route:
        receiver: Default
        group_by: ['alertname','path']
        group_wait: 15s
        group_interval: 15s
        repeat_interval: 1m

        routes:
        - receiver: AlertaWeb
          match:
            team: Web
      
      receivers:
      - name: AlertaWeb
        webhook_configs:
        - url: 'https://pruu.herokuapp.com/dump/wpwebhookweb'
      - name: Default
        webhook_configs:
        - url: 'https://pruu.herokuapp.com/dump/default'