# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
<<<<<<< HEAD
      - name: Autenticando o usuario DockerHub
=======
      - name: Authentication in the DockerHub
>>>>>>> Sincronizando Prometheus
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
<<<<<<< HEAD
      - name: Construindo e enviando para o DockerHub
=======
      - name: Build and sending for the DockerHub
>>>>>>> Sincronizando Prometheus
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            jhonthan/kube-news:latest
            jhonthan/kube-news:${{github.run_number}}
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
<<<<<<< HEAD
      - name: Definindo Kuberconfig
=======
      - name: Defining Kuberconfig
>>>>>>> Sincronizando Prometheus
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
          
<<<<<<< HEAD
      - name: Deploy Kubernetes na Digital Ocean
=======
      - name: Deploy Kubernetes on Digital Ocean
>>>>>>> Sincronizando Prometheus
        uses: Azure/k8s-deploy@v3.1
        with:
          images: jhonthan/kube-news:${{github.run_number}}
          manifests: 
            k8s/deployment.yaml
